# Generated by Django 5.2.7 on 2026-01-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_horariofuncionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='foto_local1',
            field=models.ImageField(blank=True, null=True, upload_to='prestadores/locais/'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='foto_local2',
            field=models.ImageField(blank=True, null=True, upload_to='prestadores/locais/'),
        ),
    ]
