# Generated by Django 5.2.7 on 2026-01-24 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_prestador_foto_local1_prestador_foto_local2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestador',
            name='foto_local1',
        ),
        migrations.RemoveField(
            model_name='prestador',
            name='foto_local2',
        ),
        migrations.CreateModel(
            name='FotoEstabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='prestadores/locais/', verbose_name='Foto do Ambiente')),
                ('data_upload', models.DateTimeField(auto_now=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_estabelecimento', to='accounts.prestador')),
            ],
        ),
    ]
