# Generated by Django 5.2.7 on 2026-01-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_prestador_foto_local1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
