# Generated by Django 5.2.7 on 2026-01-27 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_agendamento_data_hora_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoestabelecimento',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fotoestabelecimento',
            name='imagem',
            field=models.ImageField(upload_to='estabelecimento_fotos/'),
        ),
        migrations.AlterField(
            model_name='fotoestabelecimento',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_local', to='accounts.prestador'),
        ),
    ]
